# Generated by Django 3.2.4 on 2021-09-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسنه بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='شرح')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('qty', models.IntegerField(verbose_name='موجودی انبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ساخته شده در')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف درصدی')),
                ('cash_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='تخفیف نقدی')),
                ('category', models.ManyToManyField(max_length=200, to='products.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
